crudClientes/crudClientes/Models/AplicationBbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace crudClientes.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Cliente> Cliente { get; set; }
    }
}

crudClientes/crudClientes/Models/AplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace crudClientes.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Cliente> Cliente { get; set; }
    }
}

crudClientes/crudClientes/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace crudClientes.Models
{
    public class Cliente
    {
        [Key]
        public int IdCliente { get; set; }

        [Required(ErrorMessage = "Ingrese el nombre del cliente!")]
        [Display(Name = "Nombre del cliente")]
        public string NombreCliente { get; set; }

        [Required(ErrorMessage = "Ingrese el credito del cliente")]
        [Display(Name = "Credito :")]
        public float CreditoCliente { get; set; }

        [Required(ErrorMessage = "Ingrese una edad valida")]
        [Display(Name = "Edad :")]
        [Range(20, 50)]
        public int EdadCliente { get; set; }

        [Required(ErrorMessage = "Ingrese un correo valido")]
        [Display(Name = "Correo :")]
        [EmailAddress(ErrorMessage = "Ingrese un correo valido")]
        public string CorreoCliente { get; set; }
    }
}

crudClientes/crudClientes/Models/ErrorViewModel.cs
using System;

namespace crudClientes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

crudClientes/crudClientes/Controllers/ClienteController.cs
using crudClientes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Empleados.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ClienteController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Cliente.ToList();
            return View(displaydata);
        }

//muestra pantalla 
        public IActionResult Crear()
        {
            return View();
        }
//creacion de cliente
        

//detalle de cliente
        public async Task<IActionResult> Detalle(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getDetalleCliente = await _db.Cliente.FindAsync(id);
            return View(getDetalleCliente);
        }
    
//edicion de cliente
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getEmpDetail = await _db.Cliente.FindAsync(id);
            return View(getEmpDetail);
        }
        //este metodo sirve para guardar los datos en el update
        [HttpPost]
        public async Task<IActionResult> Editar(Cliente oldCli)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldCli);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldCli);
        }

        //eliminar cliente
        public async Task<IActionResult> Eliminar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var empDetail = await _db.Cliente.FindAsync(id);
            return View(empDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Eliminar(int id)
        {

            var getEmpDetail = await _db.Cliente.FindAsync(id);
            _db.Cliente.Remove(getEmpDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Index(string busquedaCliente)
        {
            ViewData["GetClienteDetalle"] = busquedaCliente;
            var empquery = from x in _db.Cliente select x;
            if (!String.IsNullOrEmpty(busquedaCliente))
            {
                empquery = empquery.Where(x => x.NombreCliente.Contains(busquedaCliente)
                || x.CorreoCliente.Contains(busquedaCliente));
            }
            return View(await empquery.AsNoTracking().ToListAsync());
        }
    }
}

crudClientes/crudClientes/Views/Cliente/Crear.cshtml
@model crudClientes.Models.Cliente

@{
    ViewData["Title"] = "Crear";
}

<h1>Crear</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Crear">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreCliente" class="control-label"></label>
                <input asp-for="NombreCliente" class="form-control" />
                <span asp-validation-for="NombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditoCliente" class="control-label"></label>
                <input asp-for="CreditoCliente" class="form-control" />
                <span asp-validation-for="CreditoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EdadCliente" class="control-label"></label>
                <input asp-for="EdadCliente" class="form-control" />
                <span asp-validation-for="EdadCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoCliente" class="control-label"></label>
                <input asp-for="CorreoCliente" class="form-control" />
                <span asp-validation-for="CorreoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

crudClientes/crudClientes/Views/Cliente/Detalle.cshtml
@model crudClientes.Models.Cliente

@{
    ViewData["Title"] = "Detalle";
}

<h1>Detalle</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreditoCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreditoCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EdadCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EdadCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoCliente)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

crudClientes/crudClientes/Views/Cliente/Editar.cshtml
@model crudClientes.Models.Cliente

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <input asp-for="IdCliente" class="form-control" readonly/>
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreCliente" class="control-label"></label>
                <input asp-for="NombreCliente" class="form-control" />
                <span asp-validation-for="NombreCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreditoCliente" class="control-label"></label>
                <input asp-for="CreditoCliente" class="form-control" />
                <span asp-validation-for="CreditoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EdadCliente" class="control-label"></label>
                <input asp-for="EdadCliente" class="form-control" />
                <span asp-validation-for="EdadCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorreoCliente" class="control-label"></label>
                <input asp-for="CorreoCliente" class="form-control" />
                <span asp-validation-for="CorreoCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

crudClientes/crudClientes/Views/Cliente/Eliminar.cshtml
@model crudClientes.Models.Cliente

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreditoCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreditoCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EdadCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EdadCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorreoCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorreoCliente)
        </dd>
    </dl>
    
    <form asp-action="Eliminar">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

crudClientes/crudClientes/Views/Cliente/Index.cshtml
@model IEnumerable<crudClientes.Models.Cliente>

@{
    ViewData["Title"] = "Index";
}

<h1>Clientes</h1>

<p>
    <a asp-action="Crear">Agregar Usuario</a>

</p>
<!-- Buscador -->
    <form asp-action="Index" method="GET">
    <p>
        <input type="search" placeholder="Ingrese nombre o email" name="busquedaCliente"
               value="@ViewData["GetClienteDetalle"]" style="width:500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index">Ver Todos</a>
    </p>
    </form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreditoCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EdadCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorreoCliente)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreditoCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EdadCliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CorreoCliente)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.IdCliente }) |
                    @Html.ActionLink("Detalle", "Detalle", new { id = item.IdCliente }) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.IdCliente })
                </td>
            </tr>
        }
    </tbody>
</table>

crudClientes/crudClientes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

crudClientes/crudClientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - crudClientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Cliente" asp-action="Index">crudClientes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - crudClientes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>